### ISSUE TITLE
Using this with echo?

### ISSUE THREAD

**Issue by siredwin** [go-authboss/authboss-sample#16]
I tried to incorporate this example to echo but a lot of things seem to break.
Do you have an example somewhere with this on echo?

**Comment by aarondl** [comment]
I don't actually have any examples. Maybe you could post some pieces that are breaking? Keep in mind that Authboss has it's own router, so using echo you should be using http://godoc.org/github.com/labstack/echo#Echo.Any I believe to mount the Authboss handler.

**Comment by siredwin** [comment]
h := echo.WrapHandler(ab.NewRouter())
    e.Any("/authboss", h)

This far, i figured!
All my pages don't render. Something about the templates is not right.

**Comment by aarondl** [comment]
Check the Authboss logs. May tell you something.

**Comment by siredwin** [comment]
The logs are empty. Just to be sure, is it using the old version of context? My errors seem to be context related. If that is the case i will wait for v2 release as i use Go 1.8+ now. When is the release?
