### ISSUE TITLE
Not redirecting after login

### ISSUE THREAD

**Issue by OddState** [go-authboss/authboss-sample#19]
go version: go1.10.3 windows/amd64
authboss branch: master
authboss-sample branch: master

**Issue**
When I go to the site, login and attempt to create a new post I get redirected to the login page. I re-enter the login information but get redirected to the login page again. 
What I expected was to see the "create post" page.

**Detailed Steps**
1. cloned repo from master branch
2. get deps with `go get ./...`
3. build application with `go build`
4. started application
5. in browser went to http://localhost:3000
6. click "login"
7. Enter `rick@councilofricks.com` / `1234`
8. Try and create a new post

**Comment by aarondl** [comment]
Thanks for the bug report. Turns out I had forced 2fa for those routes on and forgot to undo that after I was done testing. It's fixed in f08dc52
