### ISSUE TITLE
mailer setup problem

### ISSUE THREAD

**Issue by markbiria** [go-authboss/authboss-sample#20]
There is just a simple mistake in sample code :
in blog.go line 103
`ab.Config.Core.Mailer = defaults.LogMailer{}` 

in blog.go line 117 
`defaults.SetCore(&ab.Config, *flagAPI, false)`

it overrides the mailer with its default ...
i mean if u change line 103 to use your mailer implementation in my case mailgun

`ab.Config.Core.Mailer = mailgunmailer` 

it will be overriden to default mailer that is std.out logger ....

Thanks 👍

**Comment by aarondl** [comment]
Thanks for pointing this out. I removed the offending line because it made a very useless mailer. :)
