### ISSUE TITLE
When flagAPI is on, cannot confirm by clicking confirming url  

### ISSUE THREAD

**Issue by anh** [go-authboss/authboss-sample#21]
```
GET /auth/confirm HTTP/1.1
2018-10-08T10:37:36Z [EROR]: request error from (127.0.0.1:48610) /confirm?cnf=token-value....
: unexpected end of JSON input
failed to parse json http body
```
But doing a GET with a JSON body works
``` 
curl  -X GET -H "Content-Type: application/json" localhost:3000/auth/confirm -d '{"cnf": "token-value..."}'
```

I guess the it's caused by [1], how to disable config BodyReader for a certain url? 

[1] https://github.com/volatiletech/authboss-sample/blob/master/blog.go#L139

edit: add content-type header

**Comment by markbiria** [comment]
same problem here:
it seems generated url sends confirmation token as the key-value string but parser expects json, when flagAPI is on.
for example in this case (when flagAPI is on) you can register user with this curl command:

`curl  -X POST -H "Content-Type: application/json" localhost:3000/auth/register -d '{"name": "myyname","email": "myemail@gmail.com","password":"12345","confirm_password":"12345"}' 
`

I have also removed csrf protection from code because i couldnt figure it out how to use them when flagAPI is on. If you have an example curl with csrf token that works, please send me 

thanks , 👍

**Comment by anh** [comment]
Sure, first I use `httpie` (https://httpie.org/) instead of `curl` for feeding parameters like cookie, header and json is so painful. Using `http` with printing option `-p BHbh` is lifesaver. 

1. Get appropriate CRSF for each url 
```bash 
http -p BHbh OPTIONS :3000/auth/register 

OPTIONS /auth/register HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: localhost:3000
User-Agent: HTTPie/0.9.9

HTTP/1.1 200 OK
Content-Length: 0
Date: Tue, 09 Oct 2018 20:13:59 GMT
Set-Cookie: csrf_token=MWZ1fmXXT1VTylskfLD9CTu4sSF1rPIu1WN+hCIrokI=; Max-Age=31536000
Vary: Cookie
X-Csrf-Token: ThVXxAWl2CXRhVHzOz1cd/AnikmAaoS2vfUlA+ZeIdR/cyK6YHKXcIJPCtdHjaF+y587aPXGdpholluHxHWDlg==
```
2. Use cookie and csrf token above for the register, quick remind: `http` use `k:v` format to pass header stuffs, and `k=v` to pass form or json data:

```
http -p BHbh --json POST :3000/auth/register name="myname" email="myemail@mail.com" password="password" confirm_password="password"  \
Cookie:"csrf_token=MWZ1fmXXT1VTylskfLD9CTu4sSF1rPIu1WN+hCIrokI=" \
"X-Csrf-Token":"ThVXxAWl2CXRhVHzOz1cd/AnikmAaoS2vfUlA+ZeIdR/cyK6YHKXcIJPCtdHjaF+y587aPXGdpholluHxHWDlg=="

POST /auth/register HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 103
Content-Type: application/json
Cookie: csrf_token=MWZ1fmXXT1VTylskfLD9CTu4sSF1rPIu1WN+hCIrokI=
Host: localhost:3000
User-Agent: HTTPie/0.9.9
X-Csrf-Token: ThVXxAWl2CXRhVHzOz1cd/AnikmAaoS2vfUlA+ZeIdR/cyK6YHKXcIJPCtdHjaF+y587aPXGdpholluHxHWDlg==

{
    "confirm_password": "password", 
    "email": "myemail@mail.com", 
    "name": "myname", 
    "password": "password"
}

HTTP/1.1 307 Temporary Redirect
Content-Length: 107
Content-Type: application/json
Date: Tue, 09 Oct 2018 20:17:41 GMT
Vary: Cookie

{
    "location": "/", 
    "message": "Please verify your account, an e-mail has been sent to you.", 
    "status": "success"
}
```

3. No emailer is setup so back to the console to get the confirm link 
```html
<h1>Confirm your account</h1>
<br />
<p>Please click <a href="http://localhost:3000/auth/confirm?cnf=h-A1iPysWfQ9Mj5EYuCKZo9KJ5UccHTjqABqfL-8bw48fkUQAOhBBBbwo2V7AE5TKYYYE9QXpDLrCvImQ57Tw%3D%3D" />here</a> to confirm your account</p>
```

4. **For clicking at the link above doesn't work**, get the token (and remember to `urldecode` it by just replacing the ending `%3D%3D` with `==` and feed to the json body
 
```bash 
http -p BHbh --json GET :3000/auth/confirm cnf="h-A1iPysWfQ9Mj5EYuCKZo9KJ5UccHTjqABqfL-8bw48fkUQAOhBB-Bbwo2V7AE5TKYYYE9QXpDLrCvImQ57Tw=="

GET /auth/confirm HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 99
Content-Type: application/json
Host: localhost:3000
User-Agent: HTTPie/0.9.9

{
    "cnf": "h-A1iPysWfQ9Mj5EYuCKZo9KJ5UccHTjqABqfL-8bw48fkUQAOhBB-Bbwo2V7AE5TKYYYE9QXpDLrCvImQ57Tw=="
}

HTTP/1.1 307 Temporary Redirect
Content-Length: 93
Content-Type: application/json
Date: Tue, 09 Oct 2018 20:24:27 GMT
Set-Cookie: csrf_token=vBkhw9kqRBx1kxL9RqmTaVPKjlB3qsEBMygeIaQROVM=; Max-Age=31536000
Vary: Cookie

{
    "location": "/", 
    "message": "You have successfully confirmed your account.", 
    "status": "success"
}
```

4.  Now login with new account, but first do the OPTIONS to /auth/login to get csrf token 
```
http -p BHbh OPTIONS :3000/auth/login 

OPTIONS /auth/login HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: localhost:3000
User-Agent: HTTPie/0.9.9

HTTP/1.1 200 OK
Content-Length: 0
Date: Tue, 09 Oct 2018 20:30:11 GMT
Set-Cookie: csrf_token=rZyuxltLf9nRaMs/b2bzHqmkhqeCfYobMSD7IOZ0JRg=; Max-Age=31536000
Vary: Cookie
X-Csrf-Token: 5FD7JCX0fxTV3s2tzpxub8XHdlpJIuVS1i2jpoiW6mxJzFXifr8AzQS2BpKh+p1xbGPw/ctfb0nnDViGbuLPdA==
```
5. Login 
```
http -p BHbh POST :3000/auth/login email="myemail@mail.com" password="password" \
 Cookie:"csrf_token=rZyuxltLf9nRaMs/b2bzHqmkhqeCfYobMSD7IOZ0JRg=" \
"X-Csrf-Token":"5FD7JCX0fxTV3s2tzpxub8XHdlpJIuVS1i2jpoiW6mxJzFXifr8AzQS2BpKh+p1xbGPw/ctfb0nnDViGbuLPdA=="

POST /auth/login HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 53
Content-Type: application/json
Cookie: csrf_token=rZyuxltLf9nRaMs/b2bzHqmkhqeCfYobMSD7IOZ0JRg=
Host: localhost:3000
User-Agent: HTTPie/0.9.9
X-Csrf-Token: 5FD7JCX0fxTV3s2tzpxub8XHdlpJIuVS1i2jpoiW6mxJzFXifr8AzQS2BpKh+p1xbGPw/ctfb0nnDViGbuLPdA==

{
    "email": "myemail@mail.com", 
    "password": "password"
}

HTTP/1.1 307 Temporary Redirect
Content-Length: 16
Content-Type: application/json
Date: Tue, 09 Oct 2018 20:33:39 GMT
Set-Cookie: ab_blog=MTUzOTExNzIxOXxEdi1CQkFFQ180SUFBUkFCRUFBQUxmLUNBQUVHYzNSeWFXNW5EQVVBQTNWcFpBWnpkSEpwYm1jTUVnQVFiWGxsYldGcGJFQnRZV2xzTG1OdmJRPT185A85hn6nadOw0UHJ6YNo2IVpDy8chwOUe_MemOgnfXc=; Path=/; Expires=Thu, 08 Nov 2018 20:33:39 GMT; Max-Age=2592000
Set-Cookie: rm=MTUzOTExNzIxOXxSd3dBUkdKWWJHeGlWMFp3WWtWQ2RGbFhiSE5NYlU1MllsUjJaazlPWVZOVVZGZFBWekpRUldkVmVVZE9WR1I0T0ZKNk0yVjFZa2hFUVVRM2FYZHFZamhDY0VKeWR6MDl8RWv1BbJnc2Jm2VYolg82EJyJtJQ5Gy9JOynGyawE4Jk=; Path=/; Expires=Wed, 09 Oct 2019 20:33:39 GMT
Vary: Cookie

{
    "location": "/"
}
```
6. You're now logged in, with above 2 cookies and used them in subsequence httpie request as Cookie:"ab_blog=...;rm=..." 
``` http -p BHBh GET :3000/blogs/1/edit  Cookie:"ab_blog=...;rm=..." ``` 

Caused me a day just to figure out , HTH!

**Comment by aarondl** [comment]
Hey there guys. This is sort of a weird thing in authboss. The `dev` branch has a new config option called `Modules.ConfirmMethod` that allows you to change this. It's in commit 2eeaf34. I hope this helps you out. We also found this weird when we were using the API version of things. Re-open if there's still some confusion.

**Comment by anh** [comment]
> Hey there guys. This is sort of a weird thing in authboss. The `dev` branch has a new config option called `Modules.ConfirmMethod` that allows you to change this. It's in commit 2eeaf34. I hope this helps you out. We also found this weird when we were using the API version of things. Re-open if there's still some confusion.

I looked at that commit, however if I want user do the confirm by clicking the link in the mail box, which mean I keep GET as the `ConfirmMethod`, how can I customize the BodyReader with ReadJSON = false, or new config option like `config.Modules.ConfirmBodyReader` will help?

**Comment by aarondl** [comment]
Hey @anh. I don't think there should be an "in-between" option. It should either use the API or it should not.

In my mind the use case looks like: The user clicks a link in the e-mail, and they are taken to your front-end in elm or react or whatever (see the newly created `Mail.RootURL` feature that allows you to override the root url for e-mails). Once they get there, the front-end performs an API request with the token and confirms the user.

If you want some other behavior, I think you'd have to create your own `BodyReader` that behaves like you want it to.

Now, currently I'm against making it behave like you're suggesting but I also don't think I fully understand your use case or your requirements. I'd like to hear more about what your setup looks like and how you think it should work. Thanks!
