### ISSUE TITLE
Change routing with gorilla mux

### ISSUE THREAD

**Issue by sadiq1971** [go-authboss/authboss-sample#22]
In this project you have used /go-chi/chi for routing. How can we change it with gorrila mux.

**Comment by aarondl** [comment]
Hey @sadiq1971. This is an exercise you should complete on your own. It's easily doable. But if you cannot figure this out, doing the rest of an authboss implementation is going to be extremely difficult and I'm not interested on spending time supporting people in this way :) Sorry!
