### ISSUE TITLE
Add cookie store Maxage sample to avoid possible misleading.

### ISSUE THREAD

**Issue by raven-chen** [go-authboss/authboss-sample#30]
Propose adding `cstore.Options.MaxAge(xxx)` to the sample. 

In the sample, it says

```
	sessionStore = abclientstate.NewSessionStorer(sessionCookieName, sessionStoreKey, nil)
	cstore := sessionStore.Store.(*sessions.CookieStore)
	cstore.Options.HttpOnly = false
	cstore.Options.Secure = false
```

So we wrote `cstore.Options.Maxage = 2654000` in the project. but keep getting 500 error because of the cookie is expired. (btw return 500 on cookie expiry is too much?). then we found the session store's MaxAge is the value we set but the MaxAge in securecookie still using the initial value(12 hours). Eventually, we found the Maxage setter function in the source code. Apparently, to set MaxAge, we should use `cstore.Options.Maxage(265400)` rather than assigning the value directly.

It took us several hours to dig it out. I think it would be good to add the correct usage in the sample.

**Comment by aarondl** [comment]
Hopefully the change I made is sufficient. It's worth noting that you may want to be calling `MaxAge` on the cookiestore itself in your code, otherwise something may be missed (looking at the source code for the method).

**Comment by raven-chen** [comment]
awesome! thank you!
