### ISSUE TITLE
login and register submission return blank pages. 

### ISSUE THREAD

**Issue by jonaswouters** [go-authboss/authboss-sample#7]
Form submission always returns a blank page. No modifications are made to the project. 

`2016/07/24 16:49:33 Failed to validate XSRF Token: The CSRF token in the cookie doesn't match the one received in a form/header.`

**Comment by aarondl** [comment]
So, with a fresh clone of both authboss (`go get -u -t gopkg.in/authboss.v0`) and the sample (`go get -u -t github.com/go-authboss/authboss-sample`) I'm able to log in, delete blog posts, add blog posts. Everything works as expected.

This bug report needs to have a wealth more information to determine the cause.
The issue could be stale dependencies maybe? What version of Go (1.6.2 linux/amd64)? What version of nosurf? (2e708f2).

**Comment by jonaswouters** [comment]
Thanks for letting me check the go version. Works like a charm on go 1.6.3. Does not work on 1.7rc3
