### ISSUE TITLE
Why not authProtect the destroy handler?

### ISSUE THREAD

**Issue by golliher** [go-authboss/authboss-sample#8]
I am excited by the potential of authboss, so I have been studying your documentation and the example in order to learn.

I was curious is there is a reason the destroy handler doesn't use authProtect?   I tried adding the protection and it seems to work ok, but since I'm still learning I thought I'd ask.

* https://github.com/golliher/authboss-sample/commit/bb11f307e6e1e2393d9a7e4acfb3f40e085aec2c

**Comment by aarondl** [comment]
Yeah, there's no reason for it not to be. Feel free to PR that since you already have the code :)

**Comment by golliher** [comment]
Done.
